### ISSUE TITLE
Issue during installation of swagger stats

### ISSUE THREAD

**Issue by mhtngo** [slanatech/swagger-stats#100]
Hi, 

I am running into issues during the install (below) - any ideas? Thanks ahead.

`pm WARN deprecated request@2.88.2: request has been deprecated, see https://github.com/request/request/issues/3142
npm WARN nodejs-express-sequelize-postgresql@1.0.0 No repository field.

+ swagger-stats@0.95.17
updated 1 package and audited 302 packages in 3.397s
found 0 vulnerabilities`

**Comment by sv2** [comment]
Will remove request dependency

**Comment by mhtngo** [comment]
@sv2  thank you! This is causing install failures for me on ubuntu 18.04

**Comment by sv2** [comment]
Addressed v0.99.1
