### ISSUE TITLE
How to set my own ES index template?

### ISSUE THREAD

**Issue by arjraj2806** [slanatech/swagger-stats#111]
I love this dependency - it makes wiring into ES and Prometheus really straightforward so I want to leverage it across multiple projects, but using the same Elastic cluster and therefore need to be able to adjust the index prefix for each project - I can see that the index template specifies "api-[DATE]" as the index but is there any way to override this from the configuration? 

Thanks!

**Comment by sv2** [comment]
Thanks ! You can set prefix for ES index names using option `elasticsearchIndexPrefix`. Like this:

```javascipt
let swsOptions = {
    name: 'swagger-stats-fastify',
    version: '0.95.17',
    timelineBucketDuration: 1000,
    swaggerSpec:swaggerSpec,
    elasticsearch: 'http://127.0.0.1:9200',
    elasticsearchIndexPrefix: 'swaggerstats-'
};
```

https://github.com/slanatech/swagger-stats/blob/188c649b3a36a82760fb31f38799b60724bdc3d0/examples/fastify/fasifytest.js

**Comment by arjraj2806** [comment]
I didn't see that - thanks so much!
