### ISSUE TITLE
Is there any guide to setup Prometheus and Grafana to consume the swagger-stats/metrics?

### ISSUE THREAD

**Issue by metrue** [slanatech/swagger-stats#112]
I found following statement from README, but did not find `dashboards/prometheus` anywhere.
>See dashboards/prometheus for swagger-stats Grafana dashboards

**Comment by sv2** [comment]
Here you can find more details on Prometheus / Grafana:
https://swaggerstats.io/guide/prometheus.html

Grafana dashboard is published at 
https://grafana.com/grafana/dashboards/3091
