### ISSUE TITLE
Track multiple services at one place

### ISSUE THREAD

**Issue by shreyas-t** [slanatech/swagger-stats#115]
I have multiple services in my project. Is it possible to track all of them at one place? Or each one I should have separate swagger-stats?

**Comment by sv2** [comment]
Yes, for this ElasticSearch and Prometheus integrations can be used. You can enable these using swagger-stats options. Then swagger-stats will expose Prometheus metrics, and you can use Prometheus / Grafana to analyze metrics across all of your services. When ElasticSearch integration is enabled, swagger-stats will store information about each request/response in ElasticSearch, so you can analyze all data across all of your services in Kibana.
