### ISSUE TITLE
body response show duplicate data

### ISSUE THREAD

**Issue by Mohammedalasaad** [slanatech/swagger-stats#118]
I tesed the patch request with json_encode data and its working fine. the only thing that the data shows in strange way not as it should be.
so If we have id, and first_name, last_name etc... it shows in this way "attached image."

and It should be only one time.

<img width="1396" alt="Screenshot 2020-09-12 at 01 32 01" src="https://user-images.githubusercontent.com/48674512/92980908-08ea4a80-f498-11ea-855a-428410903a89.png">

**Comment by sv2** [comment]
swagger-stats now support data type `flattened` available in ES 7.X for body of the requests. This way we can store any body payload, and query it efficiently in ES. 
https://www.elastic.co/guide/en/elasticsearch/reference/current/flattened.html#flattened

**Comment by sv2** [comment]
Addressed in 0.95.18
