### ISSUE TITLE
Elasticsearch support

### ISSUE THREAD

**Issue by sv2** [slanatech/swagger-stats#12]
Store request/response record in ElasticSearch. Each request/response record to be individual document in the index. Index name to be time-based : sws-YYYY.MM.DD. Document structure and index template to be compatible with packetbeat http document, extending it with additional api-specific properties.

**Comment by viswanathreddy** [comment]
@sv2 Thanks for awesome work ! I am excited to contribute to this feature enhancement. May I know, how can I start contributing code?

**Comment by sv2** [comment]
Thank you, @viswanathreddy - would appreciate your help ! to start, how about you look at creating a test to validate that data is stored in Elasticsearch? one of existing tests can be used as an example. Feel free to open pull request with your test. Thanks !

**Comment by sv2** [comment]
Addressed in v0.95.0
