### ISSUE TITLE
Elasticsearch - Crash when elasticsearch's credentials are given

### ISSUE THREAD

**Issue by lafittg** [slanatech/swagger-stats#121]
Hello,
An error slipped when deploying the latest version (0.95.18)
In initTemplate of the swsElasticEmitter, (when given) the elastic auth is set on a null variable

`UnhandledPromiseRejectionWarning: TypeError: Cannot set property 'auth' of null
at swsElasticEmitter.initTemplate
`

**Comment by lafittg** [comment]
I've created a PR to fix the issue here #122

**Comment by Tomas2D** [comment]
Could you please release a new version?

**Comment by sv2** [comment]
Released v0.95.19
Thanks !
