### ISSUE TITLE
UnhandledPromiseRejectionWarning when accessing /metrics

### ISSUE THREAD

**Issue by spijs** [slanatech/swagger-stats#132]
After running npm update and thus upgrading swagger-stats to the latest release I now get the following error when accessing /metrics.  It seems to me like a dependency issue on your end, but according to Stackoverflow replacing .end with .send might already solve this issue. Reverting back to 0.95.18 did not solve the issue.

```
UnhandledPromiseRejectionWarning: TypeError [ERR_INVALID_ARG_TYPE]: The "chunk" argument must be of type string or an instance of Buffer. Received an instance of Promise
    at ServerResponse.end (_http_outgoing.js:759:13)
    at /usr/src/app/node_modules/swagger-stats/lib/swsInterface.js:212:13
    at runMicrotasks (<anonymous>)
    at processTicksAndRejections (internal/process/task_queues.js:97:5)
```

Running /metrics results in a timeout which breaks prometheus/grafana integrations.

**Comment by spijs** [comment]
Prom-client v13.1.0 was added as a dependency in package.json. Otherwise the project wouldn't even build :).

**Comment by spijs** [comment]
I've got a fix. Will create PR

**Comment by sv2** [comment]
I see, metrics() returns Promise starting from prom-client 13 ... Thanks for PR !
