### ISSUE TITLE
Add support for prom-client v14

### ISSUE THREAD

**Issue by leedm777** [slanatech/swagger-stats#147]
The prom-client module released [v14 on Sept 18](https://github.com/siimon/prom-client/blob/master/CHANGELOG.md#1400---2021-09-18). Please update swagger-stats to allow for the upgrade. The breaking changes in the prom-client release are:

> - changed: `linearBuckets` does not propagate rounding errors anymore.
> 
>   Fewer bucket bounds will be affected by rounding errors. Histogram bucket
>   labels may change. [`6f1f3b2`](https://github.com/siimon/prom-client/commit/6f1f3b24c9c21311ff33e7d4b987b40c6b304e04)
> 
> - changed: The push gateway methods `pushAdd()`, `push()` and `delete()` now
>   return Promises instead of accepting a callback:
> 
>   ```js
>   // Old:
>   gateway.pushAdd({ jobName: 'test' }, (err, resp, body) => {});
>   // New:
>   gateway
>     .pushAdd({ jobName: 'test' })
>     .then(({ resp, body }) => {})
>     .catch(err => {});
>   // or
>   const { resp, body } = await gateway.pushAdd({ jobName: 'test' });
>   ```
> 
>   [`f177b1f`](https://github.com/siimon/prom-client/commit/f177b1fd3d4db5fc48fcb1ec02d94069fffcf144)
> 
> - changed: The default `nodejs_eventloop_lag_*` metrics are now reset every time
>   they are observed. This prevents these metrics from "stabilizing" over a long
>   period of time and becoming insensitive to small changes. For more info, see
>   [#370](https://github.com/siimon/prom-client/issues/370). [`0f444cd`](https://github.com/siimon/prom-client/commit/0f444cd38e4c7074991270106c270f731bafddb8)

**Comment by sv2** [comment]
v0.99.3
