### ISSUE TITLE
Replace deprecated dependency on request

### ISSUE THREAD

**Issue by leedm777** [slanatech/swagger-stats#148]
The Request.js library has been deprecated (see https://github.com/request/request/issues/3142), and is actively pushing folks to use other libraries (see https://github.com/request/request/issues/3143).

There's currently a security vulnerability via request's dependencies, making it even more important to move to a more supported library.

```
┌───────────────┬──────────────────────────────────────────────────────────────┐
│ Moderate      │ json-schema is vulnerable to Prototype Pollution             │
├───────────────┼──────────────────────────────────────────────────────────────┤
│ Package       │ json-schema                                                  │
├───────────────┼──────────────────────────────────────────────────────────────┤
│ Patched in    │ >=0.4.0                                                      │
├───────────────┼──────────────────────────────────────────────────────────────┤
│ Dependency of │ swagger-stats                                                │
├───────────────┼──────────────────────────────────────────────────────────────┤
│ Path          │ swagger-stats > request > http-signature > jsprim >          │
│               │ json-schema                                                  │
├───────────────┼──────────────────────────────────────────────────────────────┤
│ More info     │ https://github.com/advisories/GHSA-896r-f27r-55mw            │
└───────────────┴──────────────────────────────────────────────────────────────┘
```

**Comment by steven-sheehy** [comment]
@sv2 Even with the recent dependency bumps in 0.99.4 this outdated version of `request` dependency causes security checks to fail due to the vulnerable `qs` it brings in transitively. We can do `npm up` to fix but then Dependabot wipes that package-lock.json out. Any considerations to removing `request`? This is blocking our CI from passing and we'll have to spend effort figuring out workarounds.

**Comment by sv2** [comment]
Yes, we'll replace request shortly

**Comment by sv2** [comment]
Request has been replaced with Axios - v0.99.5
