### ISSUE TITLE
Plans to support OpenTelemetry?

### ISSUE THREAD

**Issue by proffalken** [slanatech/swagger-stats#161]
Hey, this looks awesome, and the logging of data to Elastic is great, however I'm wondering if there are plans to add tracing libraries for OpenTelemetry so that we can use this with Zipkin/Jaeger/Tempo etc.

It may be this already exists and I've missed it, however as more and more projects move toward OpenTelemetry, it would be amazing to see platforms like this do the same?

**Comment by sv2** [comment]
Thank you! Yes, this is ongoing work and will be part of 1.0 release - see details in this discussion:
https://github.com/slanatech/swagger-stats/discussions/135  
This repo contains 1.X code stream while it's WIP: https://github.com/slanatech/swagger-stats-v1
Would appreciate input and suggestions 
Thanks

**Comment by proffalken** [comment]
Amazing, thanks @sv2 - I'll close this off and follow the discussion
