### ISSUE TITLE
Change default UI path

### ISSUE THREAD

**Issue by danihenrique** [slanatech/swagger-stats#17]
Hello, 

Will be nice, if is possible to change the default UI path from "/swagger-stats/ui" to "/mypathapi/stats/"
for example.

Why?

I have multiples Nodejs services running, and nginx are controlling the access, something like:
api.company.com/serviceOne -> 10.0.1:3000/serviceOne
api.company.com/serviceTwo -> 10.0.1:3001/serviceTwo
But when try api.company.com/swagger-stats, I can't have multiples Nodejs running, I have to choose
redirect just for one, like 10.0.1:3001/swagger-stats...
Any idea how to solve this? any tip?

Thanks again!

**Comment by sv2** [comment]
Hi @danihenrique ! 
Thank you ! Sure - great use case.
To address this, I'm thinking to add a configuration option to specify UI path when initializing swagger-stats middleware. So you could use it like this:

```
app.use(swStats.getMiddleware({
   uriPath: '/serviceOne',
   swaggerSpec:swaggerSpec
}));
```

This should result in accessing ui, stats and metrics like this:
```
/serviceOne/ui
/serviceOne/stats
/serviceOne/metrics
```

This should allow you to specify uri path for swagger-stats to be different for your different services. 

Let me know what do you think, and if it looks good I'll add this - should be pretty straightforward.

Thanks a lot for your feedback !

**Comment by danihenrique** [comment]
Wowwww that' s awesome!

It worked !
I just couldn't update using npm, with npm install I always got the old version, I deleted the folder inside node_modules, set to use 0.90.3 version in my package.json, and I see the files after npm install, still the old version, just weird, I have to see why....

BUT to test I downloaded the repository here and pasted on my node_modules, worked perfectly !

Thanks man!

**Comment by sv2** [comment]
Great ! Will make npm release shortly. Thanks !
