### ISSUE TITLE
Endpoint not found

### ISSUE THREAD

**Issue by bacloud22** [slanatech/swagger-stats#177]
I'm adding swagger-stats as a middleware in Fastify. So I guess this whole thing is tricky.

Reproducing the Fastify example in docs didn't work at all as it messed with other Fastify plugins (mongo and others).

But anyway, I tried the encapsulation and it didn't show any errors, so I think the Fastify part of this is fine, 

```js
const swagger = require('./config/options/swagger')
fastify.register(require('fastify-swagger'), swagger.options)
fastify.register(setSwaggerStats)
```

with 

```js
const swStats = require('swagger-stats')
const apiSpec = require('./swagger.json')
async function setSwaggerStats(fastify, opts) {
    await fastify.register(require('middie')) // or fastify-express is the same
    fastify.register(swStats.getFastifyPlugin, { swaggerSpec: apiSpec });
}
```

I also installed prom-client although I will be happy with the [native dashboard](https://github.com/slanatech/swagger-stats#built-in-api-telemetry). 

http://localhost:3000/swagger-stats/
http://localhost:3000/swagger-stats/ui
didn't show up (404)

It would be nice to provide `{debug: true}` option with some errors logged if this is feasible. 

Thanks a lot !!!

**Comment by bacloud22** [comment]
edit:
maybe worth to note, my endpoint was set through options as either `127.0.0.1:3000` or `127.0.0.1`
Also as I printed stats all are zeros:
```js
setTimeout(() => {
   console.log(swStats.getCoreStats())
}, 10000);
```

**Comment by sv2** [comment]
To enable debug logging, please set env variable `DEBUG=sws:*`. Can you share output ?

**Comment by bacloud22** [comment]
Thanks. I will share debug shortly

**Comment by bacloud22** [comment]
Very nice, this is logging:

> 2022-03-24T15:20:49.898Z sws:apistats SWS:Initialize API:added get /home (/home)
> 2022-03-24T15:20:49.898Z sws:apistats SWS:Initialize API:added get /__ping_trans (/__ping_trans)
> 2022-03-24T15:20:49.899Z sws:apistats SWS:Initialize API:added get /i18n/{locale} (/i18n/:locale)
> 2022-03-24T15:20:49.899Z sws:apistats SWS:Initialize API:added get /login (/login)
> 2022-03-24T15:20:49.899Z sws:apistats SWS:Initialize API:added post /login (/login)
> 2022-03-24T15:20:49.899Z sws:apistats SWS:Initialize API:added get /signup (/signup)
> 2022-03-24T15:20:49.900Z sws:apistats SWS:Initialize API:added post /signup (/signup)
> 2022-03-24T15:20:49.900Z sws:apistats SWS:Initialize API:added get / (/)
> 2022-03-24T15:20:49.900Z sws:apistats SWS:Initialize API:added get /private (/private)
> 2022-03-24T15:20:49.900Z sws:apistats SWS:Initialize API:added post /upload (/upload)
> 2022-03-24T15:20:49.900Z sws:apistats SWS:Initialize API:added get /tags (/tags)
> 2022-03-24T15:20:49.900Z sws:apistats SWS:Initialize API:added get /tag/{tag} (/tag/:tag)
> 2022-03-24T15:20:49.900Z sws:apistats SWS:Initialize API:added get /tag/parent/{tag} (/tag/parent/:tag)
> 2022-03-24T15:20:49.901Z sws:apistats SWS:Initialize API:added get /tag/granpa/{tag} (/tag/granpa/:tag)
> 2022-03-24T15:20:49.901Z sws:apistats SWS:Initialize API:added get /division/{division} (/division/:division)
> 2022-03-24T15:20:49.901Z sws:apistats SWS:Initialize API:added get /keyword/{keyword} (/keyword/:keyword)
> 2022-03-24T15:20:49.901Z sws:apistats SWS:Initialize API:added get /autocomplete/{keyword} (/autocomplete/:keyword)
> 2022-03-24T15:20:49.901Z sws:apistats SWS:Initialize API:added get /top/tags (/top/tags)
> 2022-03-24T15:20:49.901Z sws:apistats SWS:Initialize API:added get /top/div (/top/div)
> 2022-03-24T15:20:49.901Z sws:apistats SWS:Initialize API:added get /top/parent/tags (/top/parent/tags)
> 2022-03-24T15:20:49.901Z sws:apistats SWS:Initialize API:added get /top/granpa/tags (/top/granpa/tags)
> 2022-03-24T15:20:49.901Z sws:apistats SWS:Initialize API:added get /categories (/categories)
> 2022-03-24T15:20:49.901Z sws:apistats SWS:Initialize API:added get /about (/about)
> 2022-03-24T15:20:49.901Z sws:apistats SWS:Initialize API:added get /howto (/howto)
> 2022-03-24T15:20:49.901Z sws:apistats SWS:Initialize API:added get /policy (/policy)
> 2022-03-24T15:20:49.901Z sws:apistats SWS:Initialize API:added get /fennec-fox (/fennec-fox)
> 2022-03-24T15:20:49.901Z sws:apistats SWS:Initialize API:added get /admin/ (/admin/)
> 2022-03-24T15:20:49.901Z sws:apistats SWS:Initialize API:added post /admin/ (/admin/)
> 2022-03-24T15:20:49.901Z sws:apistats SWS:Initialize API:added get /admin/dashboard (/admin/dashboard)
> 2022-03-24T15:20:49.901Z sws:apistats SWS:Initialize API:added put /admin/{id} (/admin/:id)
> 2022-03-24T15:20:49.902Z sws:apistats SWS:Initialize API:added delete /admin/{id} (/admin/:id)
> 2022-03-24T15:20:49.902Z sws:apistats SWS:Initialize API:added patch /admin/{id} (/admin/:id)
> 2022-03-24T15:20:49.902Z sws:apistats SWS:Initialize API:added get /listings/ (/listings/)
> 2022-03-24T15:20:49.902Z sws:apistats SWS:Initialize API:added get /listings/donations (/listings/donations)
> 2022-03-24T15:20:49.902Z sws:apistats SWS:Initialize API:added post /listings/donations (/listings/donations)
> 2022-03-24T15:20:49.902Z sws:apistats SWS:Initialize API:added get /listings/skills (/listings/skills)
> 2022-03-24T15:20:49.902Z sws:apistats SWS:Initialize API:added post /listings/skills (/listings/skills)
> 2022-03-24T15:20:49.902Z sws:apistats SWS:Initialize API:added get /listings/blogs (/listings/blogs)
> 2022-03-24T15:20:49.902Z sws:apistats SWS:Initialize API:added post /listings/blogs (/listings/blogs)
> 2022-03-24T15:20:49.902Z sws:apistats SWS:Initialize API:added get /listings/id/{id}/ (/listings/id/:id/)
> 2022-03-24T15:20:49.902Z sws:apistats SWS:Initialize API:added get /listings/id/{id}/comments (/listings/id/:id/comments)
> 2022-03-24T15:20:49.902Z sws:apistats SWS:Initialize API:added post /listings/gwoogl (/listings/gwoogl)
> 2022-03-24T15:20:49.902Z sws:apistats SWS:Initialize API:added post /listings/geolocation (/listings/geolocation)
> 2022-03-24T15:20:49.902Z sws:apistats SWS:Initialize API:added get /listings/admin/check/sthtwnXLob/{id} (/listings/admin/check/sthtwnXLob/:id)
> 2022-03-24T15:20:49.902Z sws:apistats SWS:Initialize API:added post /listings/id/{id}/comment (/listings/id/:id/comment)
> 2022-03-24T15:20:49.903Z sws:apistats SWS:Initialize API:added get /listings/user (/listings/user)
> 2022-03-24T15:20:49.903Z sws:apistats SWS:Initialize API:added get /data/get_tags_en (/data/get_tags_en)
> 2022-03-24T15:20:49.903Z sws:apistats SWS:Initialize API:added get /data/get_tags_ar (/data/get_tags_ar)
> 2022-03-24T15:20:49.903Z sws:apistats SWS:Initialize API:added get /data/get_tags_fr (/data/get_tags_fr)
> 2022-03-24T15:20:49.903Z sws:apistats SWS:Initialize API:added get /data/get_donations_tags_en (/data/get_donations_tags_en)
> 2022-03-24T15:20:49.903Z sws:apistats SWS:Initialize API:added get /data/get_donations_tags_ar (/data/get_donations_tags_ar)
> 2022-03-24T15:20:49.903Z sws:apistats SWS:Initialize API:added get /data/get_donations_tags_fr (/data/get_donations_tags_fr)
> 2022-03-24T15:20:49.903Z sws:apistats SWS:Initialize API:added get /data/get_skills_tags_en (/data/get_skills_tags_en)
> 2022-03-24T15:20:49.903Z sws:apistats SWS:Initialize API:added get /data/get_skills_tags_fr (/data/get_skills_tags_fr)
> 2022-03-24T15:20:49.903Z sws:apistats SWS:Initialize API:added get /data/get_skills_tags_ar (/data/get_skills_tags_ar)
> 2022-03-24T15:20:49.903Z sws:apistats SWS:Initialize API:added post /debug/insertListing (/debug/insertListing)
> 2022-03-24T15:20:49.903Z sws:apistats SWS:Initialize API:added post /debug/insertComment (/debug/insertComment)
> 2022-03-24T15:20:49.903Z sws:apistats SWS:Initialize API:added post /debug/getComments (/debug/getComments)
> 2022-03-24T15:20:49.903Z sws:apistats SWS:Initialize API:added post /debug/getCommentById (/debug/getCommentById)
> 2022-03-24T15:20:49.903Z sws:apistats SWS:Initialize API:added post /debug/getDocumentById (/debug/getDocumentById)
> 2022-03-24T15:20:49.903Z sws:apistats SWS:Initialize API:added post /debug/getDocumentsSince (/debug/getDocumentsSince)
> 2022-03-24T15:20:49.903Z sws:apistats SWS:Initialize API:added post /debug/getDocumentsByUser (/debug/getDocumentsByUser)
> 2022-03-24T15:20:49.903Z sws:apistats SWS:Initialize API:added post /debug/getUserById (/debug/getUserById)
> 2022-03-24T15:20:49.903Z sws:apistats SWS:Initialize API:added post /debug/insertUser (/debug/insertUser)
> 2022-03-24T15:20:49.903Z sws:apistats SWS:Initialize API:added post /debug/gwoogl (/debug/gwoogl)
> 2022-03-24T15:20:49.903Z sws:apistats SWS:Initialize API:added post /debug/getDocumentsByTag (/debug/getDocumentsByTag)
> 2022-03-24T15:20:49.903Z sws:apistats SWS:Initialize API:added post /debug/getDocumentsByDivision (/debug/getDocumentsByDivision)
> 2022-03-24T15:20:49.903Z sws:apistats SWS:Initialize API:added post /debug/getDocumentsByGeolocation (/debug/getDocumentsByGeolocation)
> 2022-03-24T15:20:49.903Z sws:apistats SWS:Initialize API:added post /debug/deactivateDocument (/debug/deactivateDocument)
> 2022-03-24T15:20:49.903Z sws:apistats SWS:Initialize API:added post /debug/approveDocument (/debug/approveDocument)
> 2022-03-24T15:20:49.903Z sws:apistats SWS:Initialize API:added post /debug/reactivateDocument (/debug/reactivateDocument)
> 2022-03-24T15:20:49.903Z sws:apistats SWS:Initialize API:added post /debug/autocomplete (/debug/autocomplete)
> 2022-03-24T15:20:49.904Z sws:apistats SWS:Initialize API:added post /debug/getDocumentsByKeyword (/debug/getDocumentsByKeyword)
> 2022-03-24T15:20:49.904Z sws:apistats SWS:Initialize API:added post /debug/topTags (/debug/topTags)
> 2022-03-24T15:20:49.904Z sws:apistats SWS:Initialize API:added post /debug/topBydivision (/debug/topBydivision)
> 2022-03-24T15:20:49.904Z sws:apistats SWS:Initialize API:added post /debug/topByParentTag (/debug/topByParentTag)
> 2022-03-24T15:20:49.904Z sws:apistats SWS:Initialize API:added post /debug/topByGranpaTag (/debug/topByGranpaTag)
> 2022-03-24T15:20:49.904Z sws:apistats SWS:Initialize API:added post /debug/getDocumentsForModeration (/debug/getDocumentsForModeration)
> 2022-03-24T15:20:49.904Z sws:apistats SWS:Initialize API:added post /debug/updateDocument (/debug/updateDocument)
> 2022-03-24T15:20:49.904Z sws:apistats SWS:Initialize API:added post /debug/removeDocument (/debug/removeDocument)
> 2022-03-24T15:20:49.904Z sws:apistats SWS:Initialize API:added get /game/ (/game/)
> 2022-03-24T15:20:49.904Z sws:apistats SWS:Initialize API:added get /sthtwnXLob/visitors (/sthtwnXLob/visitors)
> 2022-03-24T15:20:49.935Z sws:elastic Error getting version: {"errno":-4078,"code":"ECONNREFUSED","syscall":"connect","address":"127.0.0.1","port":9200}
> worker 6620 died

**Comment by bacloud22** [comment]
In doc it seems optional:

> Elasticsearch URL. If specified, enables storing of request response records in Elasticsearch. Default is empty (storing to Elasticsearch is disabled).

 While in code, it is not ([this commit](https://github.com/ridakk/swagger-stats/commit/6d89a541d89a2679e06be5637c860d5649568733#diff-593da32c9e254b35439eed3a9dd453bf758a7ad030c5a32e4fd7364b742742c3R57)) then again, optional:

https://github.com/ridakk/swagger-stats/blob/6d89a541d89a2679e06be5637c860d5649568733/lib/swsUtil.js#L90

**Comment by bacloud22** [comment]
I removed token based authentication from Elastic and set it to basic (user/pass). Also removed SSL options, now my app bootstraps well; No error like before:

> 4078,"code":"ECONNREFUSED","syscall":"connect","address":"127.0.0.1","port":9200}
> worker 6620 died

However, endpoints are still not found (404).
