### ISSUE TITLE
Integrating with existing express app

### ISSUE THREAD

**Issue by cjindal-innow8** [slanatech/swagger-stats#18]
Guys,

A great APM tool. Getting it implemented in all of my new projects.
One thing I needed to ask how can I use it in my existing nodejs projects ? I have app written in express 4 and uses mysql as the DB. Any help would be highly appreciated.

Thanks

**Comment by sv2** [comment]
Thank you! 
For your existing projects, you may just add swagger-stats as a dependency, and enable swagger-stats middleware in express app. If you don't have swagger spec in existing projects, it's ok - you can initialize  swagger-stats without swagger spec, and then it will detect API operations based on express routes:

```
var swStats = require('swagger-stats');
app.use(swStats.getMiddleware({}));
```  

Hope this answers you question, if not - please share more details about your existing projects so we can review further.

Thanks!

**Comment by cjindal-innow8** [comment]
Sounds great let me try
