### ISSUE TITLE
api_index_template.json is missing in the last patch

### ISSUE THREAD

**Issue by ksamykandil** [slanatech/swagger-stats#238]
Application is not starting if they are using the latest update "**0.99.3**"

Error: Cannot find module '../schema/elasticsearch/api_index_template.json'
Require stack:
- /******/node_modules/swagger-stats/lib/swsElasticEmitter.js
- /******/node_modules/swagger-stats/lib/swsProcessor.js
- /******/node_modules/swagger-stats/lib/swsInterface.js

**Comment by tomasmalio** [comment]
Hi @ksamykandil 
I've the same problem! Did you solve it?

Thanks for your time,
Tom

**Comment by sv2** [comment]
Fixed in 0.99.4, please try

**Comment by tomasmalio** [comment]
Thanks @sv2! That's work for me!

I've updated the swagger-stats to "swagger-stats": "^0.99.4"
