### ISSUE TITLE
unit tests fail at swagger-stat@0.99.5

### ISSUE THREAD

**Issue by zhenisduissekov** [slanatech/swagger-stats#245]
with the last update suddenly most of the unit tests of our project started failing. 
<img width="851" alt="image" src="https://user-images.githubusercontent.com/52789114/212827951-15219e0d-af2c-4fea-9a72-69be8b1e9dc7.png">

tests that use a file with a const swStats = require('swagger-stats') started failing,

After returning back to older swagger-stat version (0.99.4) tests started passing successfully. 

I use installation method for Express and in package.json there is:  "swagger-stats": "^0.99.1",

please advise really depend your on your product?)

**Comment by sv2** [comment]
Seems to be related with Axios import - replaced Requests with Axios. Will address shortly.

**Comment by zhenisduissekov** [comment]
hi, any news on the issue? maybe need more input data?

**Comment by zhenisduissekov** [comment]
@sv2 hi, how is it going?

**Comment by sv2** [comment]
should be addressed v0.99.6
