### ISSUE TITLE
DEBUG env is being overridden by `lib/swsElasticEmitter.js`

### ISSUE THREAD

**Issue by shubhamp-sf** [slanatech/swagger-stats#271]
After the latest release of `v0.99.6` the DEBUG env var is being overridden. (added in this commit https://github.com/slanatech/swagger-stats/commit/dbc29e73cba343d158a989ff89203013ff0c418d.)

Resulting in all the logs being shown for the apps using debug package, regardless of what's set in their own env.

I don't think this explicit override is needed here. Please remove it.

**Comment by Cl0ser01** [comment]
can you push it to npm pls?
