### ISSUE TITLE
Support Koa framework

### ISSUE THREAD

**Issue by inxming** [slanatech/swagger-stats#33]
app.js:
    const app = require('koa')();
    const api = require('koa-router')();
    var swStats = require('swagger-stats');
    app.use(swStats.getMiddleware({}));

log：
    AssertionError: app.use() requires a generator function

**Comment by rvelaz** [comment]
@sv2 why was the issue closed? Has support to Koa been added?

**Comment by sv2** [comment]
No, support for Koa is not added yet. Reopened.

**Comment by tabarra** [comment]
Any plans or timeline on supporting Koa? Even if through koa-connect

**Comment by sv2** [comment]
Koa is supported starting from v 0.95.9
