### ISSUE TITLE
how to use swagger-stats with sails.js framework

### ISSUE THREAD

**Issue by hametGh** [slanatech/swagger-stats#39]
is there any way to use swagger-stats in sails.js framework or it is only work with express?

**Comment by sv2** [comment]
Only works with express so far. Will take a look at sail.js ...

**Comment by sv2** [comment]
Looks like sail.js is compatible with express and the same middleware can be used with sail.js:
https://sailsjs.com/documentation/concepts/middleware

Perhaps you could try to add swagger-stats as a middleware to you app per instructions on the page above ?

**Comment by hametGh** [comment]
yes it's worked with `config/express.js` 

```javascript 
const swStats = require('swagger-stats');
const apiSpec = require('../swagger.json');

module.exports.express = {
    customMiddleware: function (app) {
        app.use(swStats.getMiddleware({ swaggerSpec: apiSpec }));
    }
};
```
but know when i request to `/swagger-stats/ui` i got this error:
```
error: Server Error:
error: TypeError: res.sendFile is not a function
at Object.trackingMiddleware [as handle] (\node_modules\swagger-stats\lib\swsInterface.js:357:21)
```

**Comment by hametGh** [comment]
any solution?

**Comment by sv2** [comment]
Got it working !  I've created new starter sails.js project `sails new test-project`, selecting `Web App` template. 

Then to enable swagger-stats, modify file `config/http.js` as follows:

```
/**
 * HTTP Server Settings
 * (sails.config.http)
 *
 * Configuration for the underlying HTTP server in Sails.
 * (for additional recommended settings, see `config/env/production.js`)
 *
 * For more information on configuration, check out:
 * https://sailsjs.com/config/http
 */

let swStats = require('swagger-stats');    
let swaggerSpec = require('swagger-stats/examples/authtest/petstore.json')

module.exports.http = {

  middleware: {

    order: [
      'swaggerStats',
      'cookieParser',
      'session',
      'bodyParser',
      'compress',
      'poweredBy',
      'router',
      'www',
      'favicon'
    ],

    swaggerStats: (function _configureSwaggerStats(){
      let swsOptions = {
        name: 'swagger-stats-sailsjs',
        version: '0.1.0',
        timelineBucketDuration: 60000,
        swaggerSpec:swaggerSpec,
        durationBuckets: [50, 100, 200, 500, 1000, 5000],
        requestSizeBuckets: [500, 5000, 15000, 50000],
        responseSizeBuckets: [600, 6000, 6000, 60000],
        // Make sure both 50 and 50*4 are buckets in durationBuckets, 
        // so Apdex could be calculated in Prometheus 
        apdexThreshold: 50,    
        onResponseFinish: function(req,res,rrr){
          debug('onResponseFinish: %s', JSON.stringify(rrr));
        },
        authentication: false
      };
      return swStats.getMiddleware(swsOptions);
    })(),
  },
};

```
I'm using here example swagger spec that comes with swagger-stats, just for illustration. 
This gives  working sails.js example app with swagger-stats enabled: 

 
![image](https://user-images.githubusercontent.com/2171896/40272065-f26ec5e2-5b5b-11e8-957b-dd894ad33f26.png)

![image](https://user-images.githubusercontent.com/2171896/40272067-02e027a4-5b5c-11e8-9cab-54ba6af4406d.png)

**Comment by sv2** [comment]
Closing as no further feedback - assume above suggestion is working
