### ISSUE TITLE
Only recognizing errors running locally

### ISSUE THREAD

**Issue by dmwelch** [slanatech/swagger-stats#41]
Hi, I'm really excited about integrating this into our project but I'm running into this issue when I run locally - `swagger-stats` will report bad endpoint calls but not successful ones. 

Our project modifies the swagger object depending on the environment like so:
```javascript
import originalSwaggerObject from './swagger.json'
import { devHost, npHost, prodHost } from '../config/params'

export default () => {
  let swaggerObject = {...originalSwaggerObject}
  if (process.env.NODE_ENV === 'local_dev') {
    swaggerObject.schemes = ['http']
    swaggerObject.host = 'localhost:3000'
    swaggerObject.basePath = '/myapi'
  }
  else {
    swaggerObject.basePath = '/myapi/v2'
    if (process.env.NODE_ENV === 'dev') {
      swaggerObject.host = devHost
    }
    else if (process.env.NODE_ENV === 'np') {
      swaggerObject.host = npHost
    } else {
      swaggerObject.host = prodHost
    }
  }
  return swaggerObject
}
```
In `app.js`:
```javascript
import express from 'express'
...
import swStats from 'swagger-stats'
import SwaggerParser from 'swagger-parser'
import swaggerObj from './swagger/util'
...
const app = express()
...
let parser = new SwaggerParser()
parser.validate(swaggerObject, (err, api) => {
  if (!err) {
    logger.info('Succeeded in validating swagger file')
    app.use(swStats.getMiddleware({
      swaggerSpec: api,
      uriPath: swaggerObject.basePath,
      name: 'swagger-stats-test'
    }))
  } else {
    logger.error(err)
    logger.error('Failed to validate swagger file')
  }
})
...
```
Any ideas?

**Comment by dmwelch** [comment]
Turning on debug, I'm getting this during initialization:

> sws:apistats SWS:Initialize API:added get /myapi/abc (/myapi/abc) +0ms
>  sws:apistats SWS:Initialize API:added post /myapi/abc (/myapi/abc) +0ms
>  sws:apistats SWS:Initialize API:added get /myapi/abc/{id} (/myapi/abc/:id) +1ms
>  sws:apistats SWS:Initialize API:added put /myapi/abc/{id} (/myapi/abc/:id) +0ms
>  sws:apistats SWS:Initialize API:added patch /myapi/abc/{id} (/myapi/abc/:id) +0ms
>  sws:apistats SWS:Initialize API:added patch /myapi/abc/randomize/{id} (/myapi/abc/randomize/:id) +1ms
>  sws:apistats SWS:Initialize API:added get /myapi/xyz (/myapi/xyz) +0ms
>  sws:apistats SWS:Initialize API:added patch /myapi/xyz (/myapi/xyz) +0ms
>  sws:apistats SWS:Initialize API:added get /myapi/xyz/{id} (/myapi/xyz/:id) +0ms
>  sws:apistats SWS:Initialize API:added delete /myapi/xyz/{id} (/myapi/xyz/:id) +0ms
>  sws:apistats SWS:Initialize API:added put /myapi/elastic-search/index (/myapi/elastic-search/index) +0ms

This _looks_ correct so I'm stuck.

**Comment by sv2** [comment]
Hi ! To confirm, by running locally, do you mean mode `process.env.NODE_ENV === 'local_dev'` ?
Could you try to capture debug log for both cases - when bad api call executed ( reported by swagger-stats) and successful api call executed (not reported) ?
Also, is it possible to share your swagger-spec ?

One idea in the meantime: I am not sure why you are setting option `uriPath` in swagger-stats initialization ... This overrides swagger-stats internal API path, but you seem to to set it to base path from your swagger spec, which should not be related... try to remove it, and see if it works with default (`/swagger-stats`)

```
app.use(swStats.getMiddleware({
      swaggerSpec: api,
      name: 'swagger-stats-test'
    }))
```

**Comment by dmwelch** [comment]
I just took a look at this again, and noticed this above in the `app.js`:

```javascript
...
// setting routes
    // TODO: switch back to router if find out how to ge the server host in it
    //app.use('/', pingRouter) // smoke testing
    app.use('/sets-api/entries', entriesRouter)
    app.use('/sets-api/', setsRouter)
...
```
Once I fixed that, everything works right.  

Yeah, I'm feeling just _awesome_ right now... 🙄 #devwinning
