### ISSUE TITLE
Share promClient with parent by exposing or using peerDependencies

### ISSUE THREAD

**Issue by croeck** [slanatech/swagger-stats#61]
Hi,

could we somehow make it possible to expose our own, business related prometheus metrics, via the same URL?

Until now, our application and the express framework both use the same `prom-client` dependency, so that Prometheus must scrape only one URL to fetch all metrics.

I could imagine two approaches how one could realize this:

1) Expose the `prom-client` used by the middleware in your module
2) Declare `prom-client` as peerDependency

What do you think?

**Comment by felix-hoc** [comment]
I would love to have a solution for this. I am using custom metrics and I just have a separate `prom-client` dependency in my package.json, pointing to the same version range. But I had a problem where `swagger-stats` got updated, and with it `prom-client`, so I had two independent installs and lost my custom metrics.

I think either one of those approaches would be fine!

**Comment by felix-hoc** [comment]
Thanks for merging the PR! Would it be possible to get a release out with this?

**Comment by sv2** [comment]
Released in v.0.95.10
