### ISSUE TITLE
Support for Fastify Framework

### ISSUE THREAD

**Issue by danihenrique** [slanatech/swagger-stats#62]
Hello!

I already used Swagger Stats in a Express project. Its awesome, I loved!

Now I am working with Fastify framework, when I try to access the url I got:
```
uncaughtException   TypeError: res.status is not a function
console.ts:95
  
  - swsInterface.js:345 trackingMiddleware
    [leaderboard]/[swagger-stats]/lib/swsInterface.js:345:21
......................
```

It's possible to implementate that? or any tips how I should modify ?

Thanks again!

**Comment by jjayaraman** [comment]
I too have the same question.  Was looking swagger-stats for fastify server. Thanks

**Comment by sv2** [comment]
Released in v.0.95.11

Example how to enable swagger-stats in Fastify app:

```javascript
const swStats = require('swagger-stats');
const apiSpec = require('swagger.json');

const fastify = require('fastify')({
    logger: true
});

fastify.register(swStats.getFastifyPlugin, {swaggerSpec:apiSpec});
```
Full example:

https://github.com/slanatech/swagger-stats/blob/master/examples/fastify/fasifytest.js
