### ISSUE TITLE
Error: Cannot find module 'swagger.json'

### ISSUE THREAD

**Issue by khaderkhan** [slanatech/swagger-stats#68]
In the root directory of my nodejs application, I installed swagger-stats using 

`npm install swagger-stats --save
`
Then, in my app.js file, I required the following 3 lines: 
`var swStats = require('swagger-stats');
var apiSpec = require('swagger.json');
app.use(swStats.getMiddleware({swaggerSpec:apiSpec}));`

But I get this error:

`internal/modules/cjs/loader.js:582
    throw err;
    ^

Error: Cannot find module 'swagger.json'
    at Function.Module._resolveFilename (internal/modules/cjs/loader.js:580:15)
    at Function.Module._load (internal/modules/cjs/loader.js:506:25)
    at Module.require (internal/modules/cjs/loader.js:636:17)
    at require (internal/modules/cjs/helpers.js:20:18)
    at Object.<anonymous> (/home/p11p3/Desktop/mydir/app.js:9:15)
    at Module._compile (internal/modules/cjs/loader.js:688:30)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:699:10)
    at Module.load (internal/modules/cjs/loader.js:598:32)
    at tryModuleLoad (internal/modules/cjs/loader.js:537:12)
    at Function.Module._load (internal/modules/cjs/loader.js:529:3)
`

I'm using node version v10.12.0

Please tell me what needs to be done.

**Comment by sv2** [comment]
`swagger.json` should be a file that exists in your application
This file is not provided as part of swagger-stats package - this is swagger spec for your APIs 
See an example here: https://github.com/slanatech/swagger-stats/tree/master/examples/authtest

**Comment by khaderkhan** [comment]
Thanks for your reply. I will try that out and see if it works.

**Comment by khaderkhan** [comment]
Hi,
I have loaded the default swagger.json, the one that is provided here: https://github.com/slanatech/swagger-stats/blob/master/examples/authtest/petstore.json

And without making any changes to the json above, I'm getting the stats for my routes as and when I visit them. 

So, whats the use of creating my own swagger.json file when I'm getting the results through the default file itself?

**Comment by sv2** [comment]
You'll need to use either ElasticSearch or Prometheus to store data from all microservices ( swagger-stats supports both ). Then you can use Kibana to build dashboards base on data in ElasticSearch, or Grafana. 
See example dashboard for Grafana: https://grafana.com/dashboards?search=swagger-stats

**Comment by khaderkhan** [comment]
Hi, Thanks for your replies. 
Can you please tell me how I can store the data from my application's swagger-stats to ElasticSearch?

**Comment by sv2** [comment]
Just add option `elasticsearch` when initializing swagger-stats. The value of this option is URL of your ElasticSearch. Like this:

```
        // Enable swagger-stats middleware
        app.use(swStats.getMiddleware({
            name: 'swagger-stats-testapp',
            version: '0.95.10',
            timelineBucketDuration: tlBucket,
            uriPath: '/swagger-stats',
            swaggerSpec:swaggerSpec,
            elasticsearch: 'http://127.0.0.1:9200',
        }));
```

Sure, you can use Grafana to visualize data from ElasticSearch:
https://grafana.com/docs/features/datasources/elasticsearch/
