### ISSUE TITLE
Duration buckets not being used for Prometheus.

### ISSUE THREAD

**Issue by gombosg** [slanatech/swagger-stats#72]
Because the Prometheus histograms are [initialized](https://github.com/slanatech/swagger-stats/blob/0f861dafb051b2639a20cf7215f74902f1fe1f18/lib/swsAPIStats.js#L48) with default values before the options are read in. It looks good for the Swagger stats part but not for Prometheus.

I'll try to come up with a PR for this.

**Comment by gombosg** [comment]
This would be it
https://github.com/slanatech/swagger-stats/compare/master...gombosg:duration-buckets
What do you think?

**Comment by sv2** [comment]
Looks good, thank you !

**Comment by sv2** [comment]
Released in v.0.95.10
