### ISSUE TITLE
Support for HapiJs

### ISSUE THREAD

**Issue by imrahamed** [slanatech/swagger-stats#75]
hello

It's possible to use this awesome tool in hapi js project?

Thanks

**Comment by ronayumik** [comment]
is there any blocker on implementing this on hapi? Have you tried import this library into hapi project?

**Comment by imrahamed** [comment]
Is there any documentation or workaround for hapi implementation?

**Comment by sv2** [comment]
Hapijs support released in version 0.95.8
Here is an example how to use Hapi app:
https://github.com/slanatech/swagger-stats/blob/master/examples/hapijstest/hapijstest.js
