### ISSUE TITLE
Elasticsearch authentication support

### ISSUE THREAD

**Issue by hmshwt** [slanatech/swagger-stats#76]
Hi,
I needed to push the request/response data to a Elasticsearch cluster that does not permit anonymous access. The 'request' npm module used in https://github.com/slanatech/swagger-stats/blob/e38ca7aa5d9c21b076cd754d1dee4ce598610bc8/lib/swsElasticEmitter.js#L11 can be configured to add an authentication header. 

If this is something that benefits other users, I would like to open a pull request.

Thank you

**Comment by sv2** [comment]
Sounds good, thanks!

**Comment by sv2** [comment]
You can specify options `elasticsearchUsername` and `elasticsearchPassword` when initializing swagger-stats. This enables authentication with ElasticSearch.

**Comment by sv2** [comment]
Available in v.0.95.10
