### ISSUE TITLE
Error: Cannot find module '@hapi/inert'

### ISSUE THREAD

**Issue by felix-hoc** [slanatech/swagger-stats#79]
I'm getting the following error when using the newly released swagger-stats@0.95.8 as a dependency:

> Error: Cannot find module '@hapi/inert'

This crashes the node process.
Looks like "@hapi/inert" is specified as a devDependency, but still required in production here:
https://github.com/slanatech/swagger-stats/blob/c1f5d0ddc3bf950370f176731095bdfae3caae32/lib/swsHapi.js#L7

However, Inert does not seem to be used at all in this file.

A temporary workaround is to add @hapi/inert as a dependency yourself.

**Comment by sv2** [comment]
Thanks. Yes, @hapi/inert is needed. I did not include it as dependency to package as application may not be using hapi. Will document and see how to improve it.

**Comment by yuric18** [comment]
Same issue here, adding the @hapi/inert dependency manually as a workaround.

**Comment by sv2** [comment]
Addressed in 0.95.9 - Inert dependency removed
