### ISSUE TITLE
Usage with Nest.js

### ISSUE THREAD

**Issue by MaxVinogradov** [slanatech/swagger-stats#83]
Maybe it will be good to add docs, how to use swagger-stats with  Nest.js?
It has specific library-plugin for this - https://docs.nestjs.com/recipes/swagger .

```
  const document = SwaggerModule.createDocument(app, options);
```

document here is JS object - swagger 2.0 .

**Comment by atjeff** [comment]
@MaxVinogradov I was able to achieve this by querying the swagger json via an api client, and then passing that json result to the 
```
const { data } = await axios.get('/swagger-json`)
swaggerStats.getMiddleware({ swaggerSpec: data})
```

**Comment by mghstehr** [comment]
Does calling
`const document = SwaggerModule.createDocument(app, options);`
not deliver the data you need ?

**Comment by MaxVinogradov** [comment]
@atjeff @mghstehr , all is okay, I've just proposed to include this info into docs

**Comment by magiclen** [comment]
Using `swagger-stats` in `NestJS` with the `express` platform seems okay. But I got no luck with the other platform, `fastify`.

The fastify plugin of `swagger-stats` needs to be used with `fastify-express`. But `fastify-express` cannot be registered to `NestJS` because `the decorator 'use' has already been added!`.

**Comment by rudemex** [comment]
To implement swagger-stats in NestJS, it is not necessary to make a request, just pass the variable containing the document creation and it works.

Demo: https://rudemex-nestjs-starter.herokuapp.com/swagger-stats/

```ts
// ./src/main.ts

import { NestFactory } from '@nestjs/core';
import { SwaggerModule, DocumentBuilder } from '@nestjs/swagger';
import * as swaggerStats from 'swagger-stats';

import { AppModule } from './app.module';

async function bootstrap() {
  const app = await NestFactory.create(AppModule);

  const config = new DocumentBuilder()
    .setTitle('Cats example')
    .setDescription('The cats API description')
    .setVersion('1.0')
    .addTag('cats')
    .build();
  const document = SwaggerModule.createDocument(app, config);

  app.use(swaggerStats.getMiddleware({ swaggerSpec: document }));

  SwaggerModule.setup('api', app, document);

  await app.listen(3000);
}
bootstrap();

```

**Comment by muhammadzadeh** [comment]
It's not compatible with NestJs/Fastify adapter?

![image](https://user-images.githubusercontent.com/10474363/220642010-56c2d7c3-027b-4591-ae1d-e213852c8710.png)

**Comment by dgastudio** [comment]
> It's not compatible with NestJs/Fastify adapter?
> 
> 
> 
> ![image](https://user-images.githubusercontent.com/10474363/220642010-56c2d7c3-027b-4591-ae1d-e213852c8710.png)
> 
> 

Same question

**Comment by muhammadzadeh** [comment]
@dgastudio the problem was fixed by adding a slash(/) at the end of the address.
`example.com/stats` throw error.
`example.com/stats/` works fine.

**Comment by RomaLetodiani** [comment]
> [@dgastudio](https://github.com/dgastudio?rgh-link-date=2023-05-07T07%3A35%3A25.000Z) the problem was fixed by adding a slash(/) at the end of the address. `example.com/stats` throw error. `example.com/stats/` works fine.

Still same right now
