### ISSUE TITLE
openapi3 basePath was removed

### ISSUE THREAD

**Issue by psyren** [slanatech/swagger-stats#84]
Request are recognized as non-swagger, because basePath is not available in spec. 

https://github.com/slanatech/swagger-stats/blob/master/lib/swsAPIStats.js
`swsAPIStats.prototype.initBasePath = function(swaggerSpec) {`
`this.basePath = swaggerSpec.basePath ? swaggerSpec.basePath : '/';`

Easy workaround add this parameter to configuration.

**Comment by sv2** [comment]
Addressed in 0.95.16 - added option `basePath` to specify base path as needed when Openapi 3.0 spec is used.
