### ISSUE TITLE
There's a way to exclude or obfuscate fields from request?

### ISSUE THREAD

**Issue by VictorCamargo** [slanatech/swagger-stats#90]
First of all, thats a awesome package, thank you!

I have a token being sent from client, and don't want to record this on swagger-stats since a dev can navigate and sell all the requests.

For example:

```
{
  http: {
    request: {
      headers: {
        x-auth-token: "***" // I want to exclude or obfuscate this 
      }
    }
  }
}
```

There's any way to achieve this?

**Comment by sv2** [comment]
Thanks ! Sure, when initializing swagger-stats you can pass callback `onResponseFinish` in options. 
request-response record will be passed as a parameter to this callback, and you can remov, add or modify any attributes needed. Here is an example:

```
        var swsOptions = {
            name: 'swagger-stats-spectest',
            version: '0.95.15',
            hostname: "hostname",
            ip: "127.0.0.1",
            timelineBucketDuration: tlBucket,
            swaggerSpec:swaggerSpec,
            uriPath: '/swagger-stats',
            durationBuckets: [10, 25, 50, 100, 200],
            requestSizeBuckets: [10, 25, 50, 100, 200],
            responseSizeBuckets: [10, 25, 50, 100, 200],
            apdexThreshold: 25,
            onResponseFinish: function(req,res,rrr){

                // You can remove non-needed or private attributes from Request Response Record
                delete rrr.http.request.headers['user-agent'];

                // You can also extend Request Response Record with custom attributes

                rrr.attrs = {
                    test1: "test1",
                    test2: "test2",
                    test3: 10,
                    test4: true,
                    test5: {prop:"value"}
                };
                debug('onResponseFinish: %s', JSON.stringify(rrr));
            }
        };
```

**Comment by VictorCamargo** [comment]
> Thanks ! Sure, when initializing swagger-stats you can pass callback `onResponseFinish` in options.
> request-response record will be passed as a parameter to this callback, and you can remove, add or modify any attributes needed. Here is an example:
> 
> ```
>         var swsOptions = {
>             name: 'swagger-stats-spectest',
>             version: '0.95.15',
>             hostname: "hostname",
>             ip: "127.0.0.1",
>             timelineBucketDuration: tlBucket,
>             swaggerSpec:swaggerSpec,
>             uriPath: '/swagger-stats',
>             durationBuckets: [10, 25, 50, 100, 200],
>             requestSizeBuckets: [10, 25, 50, 100, 200],
>             responseSizeBuckets: [10, 25, 50, 100, 200],
>             apdexThreshold: 25,
>             onResponseFinish: function(req,res,rrr){
> 
>                 // You can remove non-needed or private attributes from Request Response Record
>                 delete rrr.http.request.headers['user-agent'];
> 
>                 // You can also extend Request Response Record with custom attributes
> 
>                 rrr.attrs = {
>                     test1: "test1",
>                     test2: "test2",
>                     test3: 10,
>                     test4: true,
>                     test5: {prop:"value"}
>                 };
>                 debug('onResponseFinish: %s', JSON.stringify(rrr));
>             }
>         };
> ```

This is exactly what i need! Thank you for the really quick answer.
